// This configuration is automatically generated and populated by Firebase Studio
// Do not edit this file manually.

export function getFirebaseConfig() {
  const firebaseConfig = {
    apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
    authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
    projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
    storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
    messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
    appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
  };

  // If the config is not set, throw an error.
  // This is a critical error, as the app cannot function without Firebase config.
  if (!firebaseConfig.apiKey) {
    throw new Error('Firebase config is not set. Please check your .env file or environment variables.');
  }

  return firebaseConfig;
}
