// This configuration is automatically generated and populated by Firebase Studio
// Do not edit this file manually.

export function getFirebaseConfig() {
  const firebaseConfig = {
    apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
    authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
    projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
    storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
    messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
    appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
  };

  // If the config is not set, return null. The app will handle this gracefully.
  if (!firebaseConfig.apiKey) {
    console.warn("Firebase configuration is missing. App will run in a degraded mode.");
    return null;
  }

  return firebaseConfig;
}
