// This configuration is automatically generated and populated by Firebase Studio
// Do not edit this file manually.

export function getFirebaseConfig() {
  const firebaseConfig = {
    apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
    authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
    projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
    storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
    messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
    appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
  };

  // If the config is not set, return a dummy config to avoid app crash
  // and show a specific error on auth attempts.
  if (!firebaseConfig.apiKey) {
    console.warn("Firebase configuration is missing. Using placeholder credentials. Authentication will fail.");
    return {
      apiKey: "dummy-key",
      authDomain: "dummy-project.firebaseapp.com",
      projectId: "dummy-project",
      storageBucket: "dummy-project.appspot.com",
      messagingSenderId: "0",
      appId: "1:0:web:dummy-app-id",
    };
  }

  return firebaseConfig;
}
